-- Add new profile fields to the users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter_profile_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS personal_website_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS interests JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS education JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS work_experience JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_completion INTEGER DEFAULT 0;

-- Change bio column type from VARCHAR(500) to TEXT for longer bios
ALTER TABLE users ALTER COLUMN bio TYPE TEXT;
